---
- name: Ensure htpasswd-related utilities are installed (Red Hat)
  yum: "pkg={{ item }} state=present enablerepo=epel"
  with_items:
    - httpd-tools
    - python-passlib
  when: ansible_os_family == 'RedHat'

- name: Import Kibana GPG key
  rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
  when: ansible_os_family == 'RedHat'

- name: Build Kibana Repository
  yum_repository:
    name: kibana-{{ kibana_version }}
    description: Kibana repository for {{ kibana_version }}.x packages
    baseurl: http://packages.elastic.co/kibana/{{ kibana_version }}/centos
    gpgcheck: yes
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
  when: ansible_os_family == 'RedHat'
